Repository etcd-io/website, pull requests merged in 2021-03, with the labels that each got.

#123 Upgrading to Hugo 0.81.0
  .gitignore
  Makefile
  netlify.toml
Labels: infrastructure

#128 updating netlify.toml
  netlify.toml
Labels: docsy, infrastructure

#133 Use latest Node LTS version
  .nvmrc
Labels: infrastructure

#136 Add x-robots-tag to head for branch deploys
  netlify.toml
Labels: infrastructure

#153 Updating Makefile, .gitignore
  .gitignore
  .htmltest.external.yml
  Makefile
  check_hugo.sh
Labels: infrastructure

#154 Revise Versioning Structure v2 --> v2.3
  config.toml
  content/docs/v2.3/04_to_2_snapshot_migration.md
  content/docs/v2.3/README.md
  content/docs/v2.3/_index.md
  content/docs/v2.3/admin_guide.md
  content/docs/v2.3/api.md
  content/docs/v2.3/auth_api.md
  content/docs/v2.3/authentication.md
  content/docs/v2.3/backward_compatibility.md
  content/docs/v2.3/benchmarks/_index.md
  content/docs/v2.3/benchmarks/etcd-2-1-0-alpha-benchmarks.md
  content/docs/v2.3/benchmarks/etcd-2-2-0-benchmarks.md
  content/docs/v2.3/benchmarks/etcd-2-2-0-rc-benchmarks.md
  content/docs/v2.3/benchmarks/etcd-2-2-0-rc-memory-benchmarks.md
  content/docs/v2.3/benchmarks/etcd-3-demo-benchmarks.md
  content/docs/v2.3/benchmarks/etcd-3-watch-memory-benchmark.md
  content/docs/v2.3/benchmarks/etcd-storage-memory-benchmark.md
  content/docs/v2.3/branch_management.md
  content/docs/v2.3/clustering.md
  content/docs/v2.3/configuration.md
  content/docs/v2.3/dev/_index.md
  content/docs/v2.3/dev/release.md
  content/docs/v2.3/discovery_protocol.md
  content/docs/v2.3/docker_guide.md
  content/docs/v2.3/errorcode.md
  content/docs/v2.3/etcd_alert.rules
  content/docs/v2.3/etcd_alert.rules.yml
  content/docs/v2.3/faq.md
  content/docs/v2.3/glossary.md
  content/docs/v2.3/internal-protocol-versioning.md
  content/docs/v2.3/libraries-and-tools.md
  content/docs/v2.3/members_api.md
  content/docs/v2.3/metrics.md
  content/docs/v2.3/other_apis.md
  content/docs/v2.3/platforms/_index.md
  content/docs/v2.3/platforms/freebsd.md
  content/docs/v2.3/production-users.md
  content/docs/v2.3/proxy.md
  content/docs/v2.3/reporting_bugs.md
  content/docs/v2.3/rfc/v3api.md
  content/docs/v2.3/runtime-configuration.md
  content/docs/v2.3/runtime-reconf-design.md
  content/docs/v2.3/security.md
  content/docs/v2.3/tuning.md
  content/docs/v2.3/upgrade_2_1.md
  content/docs/v2.3/upgrade_2_2.md
  content/docs/v2.3/upgrade_2_3.md
  layouts/index.redirects
  layouts/partials/docs/hero.html
  layouts/partials/docs/nav-panel.html
Labels: cleanup/refactoring

#157 NPM: add netlify-cli and build scripts
  package.json
Labels: infrastructure

#162 Use npm scripts to build and serve, update README
  Makefile
  README.md
  check-hugo.sh
  content/blog/jepsen-343-results.md
  netlify.toml
  package.json
Labels: infrastructure

#165 Drop doc/v*/README.md files
  config.toml
  content/docs/v2.3/README.md
  content/docs/v3.1/README.md
  content/docs/v3.1/benchmarks/README.md
  content/docs/v3.2/README.md
  content/docs/v3.2/benchmarks/README.md
  content/docs/v3.4/README.md
  content/docs/v3.4/benchmarks/README.md
Labels: cleanup/refactoring

#166 updating references to client v2 to link to v2
  content/docs/next/integrations.md
  content/docs/v2.3/clustering.md
  content/docs/v2.3/libraries-and-tools.md
  content/docs/v3.1/libraries-and-tools.md
  content/docs/v3.2/integrations.md
  content/docs/v3.3/integrations.md
  content/docs/v3.4/integrations.md
Labels: cleanup/refactoring

#167 Updating README.md
  README.md
Labels: cleanup/refactoring

#172 Moving redirects: `netlify.toml` → `layouts/index.redirects`
  layouts/index.redirects
  netlify.toml
Labels: cleanup/refactoring, infrastructure
