Repository etcd-io/website, pull requests merged in 2021-04, with the labels that each got.

#182 Template cleanup: avoid generating excessive whitespace
  layouts/_default/baseof.en.html
  layouts/docs/section.en.html
  layouts/docs/single.en.html
  layouts/partials/docs/dashboard.html
  layouts/partials/docs/hero.html
  layouts/partials/docs/listing.html
  layouts/partials/docs/nav-panel.html
  layouts/partials/docs/navbar.html
  layouts/partials/docs/toc.html
  layouts/shortcodes/versions.html
Labels: cleanup/refactoring

#205 Update .editorconfig: enforce trimming whitespace
  .editorconfig
Labels: cleanup/refactoring

#209 Homepage tweaks
  content/en/_index.html
Labels: docsy

#212 Upgrade to Hugo 0.82.0
  Makefile
  netlify.toml
Labels: infrastructure

#227 Drop About from docsy MVP, and make link checker happy
  config.toml
  content/en/_index.html
Labels: docsy

#232 Add etcd favicon
  config.toml
  layouts/partials/favicons.html
Labels: docsy

#237 Add page warning for all doc version pages other than latest
  assets/scss/_alerts.scss
  assets/scss/_styles_project.scss
  assets/scss/_variables_project.scss
  config.toml
  content/en/docs/next/_index.md
  content/en/docs/v2.3/_index.md
  content/en/docs/v3.1/_index.md
  content/en/docs/v3.2/_index.md
  content/en/docs/v3.3/_index.md
  layouts/partials/version-banner.html
Labels: docsy

#240 Site 404 page
  layouts/404.html
Labels: docsy

#242 Reinstate metrics
  content/en/docs/next/metrics.md
  content/en/docs/v3.1/metrics.md
  content/en/docs/v3.2/metrics.md
  content/en/docs/v3.3/metrics.md
  content/en/docs/v3.4/metrics.md
  layouts/shortcodes/metrics-list.html
Labels: docsy

#243 Remove obsolete comment
  layouts/partials/footer.html
Labels: docsy

#248 updating config.toml
  config.toml
Labels: docsy

#250 Reenable analytics
  config.toml
Labels: docsy

#254 converting config file from toml to yaml
  config.toml
  config.yaml
Labels: enhancement

#261 Config: taxonomyTerm --> term
  config.yaml
Labels: cleanup

#258 Updating footer copyright date to match LICENSE
  layouts/partials/footer.html
Labels: cleanup

#259 Updating author frontmatter format
  content/en/blog/2020/jepsen-343-results.md
Labels: cleanup

#255 Removing raw urls where found
  content/en/docs/next/branch_management.md
  content/en/docs/v2.3/admin_guide.md
  content/en/docs/v2.3/branch_management.md
  content/en/docs/v3.1/branch_management.md
  content/en/docs/v3.2/branch_management.md
  content/en/docs/v3.3/branch_management.md
  content/en/docs/v3.4/branch_management.md
Labels: cleanup

#257 Correcting UI feedback links
  config.yaml
Labels: cleanup

#262 Remove 3.3 metrics file from 3.4 docs
  content/en/docs/v3.4/metrics/latest
Labels: cleanup

#263 Eliminate Hugo warning about .Page.Dir
  layouts/shortcodes/metrics-list.html
Labels: infrastructure
