Repository etcd-io/website, pull requests merged in 2021-07, with the labels that each got.

#404 Update npm packages to avoid high severity vulnerabilities
  package.json
Labels: infrastructure

#405 Fix link checking following v3.5 release
  Makefile
Labels: infrastructure

#407 Link-checking command cleanup and fixes for macOS 10.15+
  .gitignore
  .htmltest.external.yml
  .htmltest.yml
  Makefile
  package.json
Labels: infrastructure

#408 Makefile: drop obsolete target
  Makefile
Labels: infrastructure

#409 Netlify config: drop unnecessary x-robots-tag
  netlify.toml
Labels: infrastructure

#412 Updating `etcdctl endpoints status` output table
  content/en/docs/v3.5/demo.md
Labels: cleanup/refactoring

#388 Pruning unneeded static/apispec/swagger and css partial
  layouts/partials/css.html
  static/apispec/swagger/rpc.swagger.json
  static/apispec/swagger/v3election.swagger.json
  static/apispec/swagger/v3lock.swagger.json
Labels: cleanup/refactoring, docsy

#416 Cleanup of partials that are no longer used under docsy theming
  layouts/partials/deprecation-warning.html
  layouts/partials/docs/hero.html
  layouts/partials/home/hero.html
Labels: cleanup/refactoring

#418 NPM script cleanup
  README.md
  package.json
Labels: infrastructure

#421 Misc link updates
  content/en/blog/2021/announcing-etcd-3.5.md
  content/en/docs/v2.3/api.md
Labels: cleanup/refactoring

#423 Community page, section heading tweak: rename "Contribute" to "Contributing"
  content/en/community/_index.md
Labels: copyedit

#424 Use the hugo-extended package
  README.md
  netlify.toml
  package.json
Labels: infrastructure
