Repository etcd-io/website, pull requests merged in 2021-05, with the labels that each got.

#281 Delete unused nav-panel.html
  layouts/partials/docs/nav-panel.html
Labels: cleanup/refactoring

#282 Config: cleanup and rename default branch to main
  config.yaml
Labels: cleanup/refactoring, infrastructure

#289 Fix preview builds
  Makefile
  netlify.toml
  package.json
Labels: infrastructure

#293 Download pages: line-wrap markdown
  content/en/docs/next/dl-build.md
  content/en/docs/v3.3/dl_build.md
  content/en/docs/v3.4/dl-build.md
Labels: cleanup/refactoring

#292 Package.json cleanup: remove unused bulma et al
  package.json
Labels: cleanup/refactoring, infrastructure

#301 Doc-version landing page: line-wrap paragraphs
  content/en/docs/next/_index.md
  content/en/docs/v2.3/_index.md
  content/en/docs/v3.1/_index.md
  content/en/docs/v3.2/_index.md
  content/en/docs/v3.4/_index.md
Labels: cleanup/refactoring

#305 Homepage CTA buttons: replace GH by Learn more
  content/en/_index.html
Labels: design, ux

#321 Add psubstr shortcode
  layouts/shortcodes/psubstr.html
Labels: infrastructure

#324 Netlify previews: also build draft and future pages
  package.json
Labels: infrastructure

#327 Disable CI link checking until we get it fully working
  package.json
Labels: infrastructure

#331 v3.5 blog copyedits for opening paragraphs
  content/en/blog/2021/announcing-etcd-3.5.md
Labels: blog

#333 Install page updates for versions older than 'next'
  config.yaml
  content/en/docs/v3.1/install.md
  content/en/docs/v3.2/install.md
  content/en/docs/v3.3/dl_build.md
  content/en/docs/v3.3/install.md
  content/en/docs/v3.4/install.md
  layouts/index.redirects
Labels: cleanup/refactoring

#336 Reinstate link checking for preview builds
  .htmltest.external.yml
  .htmltest.yml
  Makefile
  config.yaml
  content/en/docs/v3.4/quickstart.md
  package.json
Labels: infrastructure

#337 API reference update
  content/en/docs/next/dev-guide/api_concurrency_reference_v3.md
  content/en/docs/next/dev-guide/api_reference_v3.md
  content/en/docs/v3.4/dev-guide/api_concurrency_reference_v3.md
  content/en/docs/v3.4/dev-guide/api_reference_v3.md
Labels: cleanup/refactoring

#313 Community page
  assets/scss/_styles_project.scss
  config.yaml
  content/en/community/_index.md
  layouts/community/list.html
  layouts/shortcodes/cards.html
Labels: enhancement
