Repository etcd-io/website, pull requests merged in 2021-09, with the labels that each got.

#483 Only fingerprint offline search data in production mode
  layouts/partials/search-input.html
Labels: infrastructure

#484 Offline search: only hash data in production
  layouts/partials/search-input.html
Labels: infrastructure

#492 Style: external-link icon tweak
  assets/scss/_styles_project.scss
Labels: design

#493 Style fix of offline-search popup close button, w/o a docsy override
  assets/js/offline-search.js
  assets/scss/_styles_project.scss
Labels: cleanup/refactoring, docsy, design

#497 Improved sidebar indentation
  assets/scss/_styles_project.scss
Labels: docsy, design

#468 Converted the page Platforms/Amazon Web Services into blog post
  content/en/blog/2017/etcd-deployments-on-AWS.md
  content/en/docs/v3.5/platforms/aws.md
  layouts/index.redirects
Labels: blog
