Repository etcd-io/website, pull requests merged in 2021-08, with the labels that each got.

#430 Drop obsolete check-hugo script
  check-hugo.sh
  package.json
Labels: infrastructure, cleanup/refactoring

#432 removing unneeded layouts/robots.txt file
  layouts/robots.txt
Labels: cleanup/refactoring

#436 removing unused about.md file
  content/en/about.md
Labels: cleanup/refactoring

#439 Consolidate CI and regular link-check commands
  Makefile
  README.md
  package.json
Labels: infrastructure

#442 CI: fix command-not-found error
  Makefile
Labels: infrastructure

#440 Upgrade Hugo to 0.87.0, and netlify-cli to v6
  package.json
Labels: infrastructure

#452 NPM script updates: ensure that check-links first builds, add submodule:update
  package.json
Labels: infrastructure

#403 Adding Lunr Search
  assets/js/offline-search.js
  config.yaml
  content/en/docs/v2.3/_index.md
  content/en/docs/v3.1/_index.md
  content/en/docs/v3.2/_index.md
  content/en/docs/v3.3/_index.md
  content/en/docs/v3.4/_index.md
  content/en/docs/v3.5/_index.md
Labels: enhancement, docsy

#456 Streamline link-checking build config and commands
  .htmltest.external.yml
  .htmltest.yml
  Makefile
  netlify.toml
  package.json
Labels: infrastructure

#420 Render-link hook: don't rewrite paths
  layouts/_default/_markup/render-link.html
Labels: infrastructure, cleanup/refactoring
