Repository etcd-io/website, pull requests merged in 2024-12, with the labels that each got.

#922 update robustness meeting time
  content/en/community/_index.md
Labels: size/XS, approved, needs-ok-to-test

#928 fix fio blogpost link
  content/en/docs/v3.4/faq.md
  content/en/docs/v3.4/op-guide/hardware.md
  content/en/docs/v3.5/faq.md
  content/en/docs/v3.5/op-guide/hardware.md
  content/en/docs/v3.6/faq.md
  content/en/docs/v3.6/op-guide/hardware.md
Labels: size/S, approved, needs-ok-to-test

#933 [v3.4] Update installation version to latest tag (v3.4.35)
  content/en/docs/v3.4/_index.md
Labels: size/XS, approved

#934 [v3.5] Update installation version to latest tag (v3.5.17)
  content/en/docs/v3.5/_index.md
Labels: size/XS, approved
