Repository etcd-io/website, pull requests merged in 2024-09, with the labels that each got.

#887 markdownlint: force gawk to run for awk match instructions
  scripts/markdown_diff_lint.sh
Labels: size/XS, approved, lgtm

#892 Add ivanvc to etcd website reviewers
  OWNERS
Labels: size/XS, approved, lgtm

#891 Update npm dependencies
  package.json
Labels: size/XS, approved

#893 Update how-to-conduct-elections.md
  content/en/docs/v3.5/tutorials/how-to-conduct-elections.md
  content/en/docs/v3.6/tutorials/how-to-conduct-elections.md
Labels: approved, size/M, needs-ok-to-test, lgtm

#894 [v3.4] Update installation version to latest tag (v3.4.34)
  content/en/docs/v3.4/_index.md
Labels: size/XS, approved

#895 [v3.5] Update installation version to latest tag (v3.5.16)
  content/en/docs/v3.5/_index.md
Labels: size/XS, approved

#900 add partial for version banner
  config.yaml
  content/en/docs/v3.4/_index.md
  layouts/partials/version-banner.html
Labels: approved, size/M

#899 added WG etcd operator community meetings to community section
  content/en/community/_index.md
Labels: size/S, approved, ok-to-test

#902 Update community page
  content/en/community/_index.md
Labels: size/S, approved
