Repository etcd-io/website, pull requests merged in 2024-06, with the labels that each got.

#808 Update how-to-create-locks.md
  content/en/docs/v3.6/tutorials/how-to-create-locks.md
Labels: size/S

#845 github/workflows: introduce action to update version tag
  .github/workflows/update-release-version-template.yaml
  .github/workflows/update-release-version.yaml
  Makefile
  scripts/update_release_version.sh
Labels: enhancement

#861 [v3.5] Update installation version to latest tag (v3.5.14)
  content/en/docs/v3.5/_index.md
Labels: size/XS

#860 [v3.4] Update installation version to latest tag (v3.4.33)
  content/en/docs/v3.4/_index.md
Labels: size/XS

#863 Bump netlify-cli to resolve cve
  .github/dependabot.yml
  package.json
Labels: size/XS

#868 Fix dependabot config to ensure allow is an array
  .github/dependabot.yml
Labels: size/XS
