Repository etcd-io/website, pull requests merged in 2024-08, with the labels that each got.

#873 fix: update grpc_naming.md for using etcd discovery with go-grpc code…
  content/en/docs/v3.5/dev-guide/grpc_naming.md
  content/en/docs/v3.6/dev-guide/grpc_naming.md
Labels: approved, size/M

#876 fix: update v3.4 grpc_naming.md guide
  content/en/docs/v3.4/dev-guide/grpc_naming.md
Labels: size/S, approved

#879 Add Markdown diff linter
  .markdownlint-cli2.yaml
  Makefile
  scripts/markdown_diff_lint.sh
Labels: approved, size/L

#880 fix dash replace on flags docs <=3.4
  config.yaml
Labels: size/XS, approved

#881 Fix typo
  content/en/docs/v3.3/op-guide/maintenance.md
  content/en/docs/v3.4/op-guide/maintenance.md
  content/en/docs/v3.5/op-guide/maintenance.md
  content/en/docs/v3.6/op-guide/maintenance.md
Labels: size/S, approved

#883 update doc auth design with simple token known issue
  content/en/docs/v3.4/learning/design-auth-v3.md
  content/en/docs/v3.5/learning/design-auth-v3.md
  content/en/docs/v3.6/learning/design-auth-v3.md
Labels: size/XS, approved
