Repository etcd-io/website, pull requests merged in 2024-07, with the labels that each got.

#866 Update doc of listen-client-urls and listen-client-http-urls
  content/en/docs/v3.4/op-guide/configuration.md
  content/en/docs/v3.5/op-guide/configuration.md
  content/en/docs/v3.6/op-guide/configuration.md
Labels: size/S, approved

#872 Improvements to the GitHub update release version workflow
  scripts/update_release_version.sh
Labels: approved, size/M

#874 [v3.5] Update installation version to latest tag (v3.5.15)
  content/en/docs/v3.5/_index.md
Labels: size/XS, approved
