Repository etcd-io/website, pull requests merged in 2025-08, with the labels that each got.

#1053 Update correct link for etcd-cpp-apiv3 (credit to @rajachan)
  content/en/docs/v3.5/integrations.md
  content/en/docs/v3.6/integrations.md
  content/en/docs/v3.7/integrations.md
Labels: size/XS, approved

#1052 Remove bitnami chart reference from docs
  content/en/docs/v3.5/install.md
  content/en/docs/v3.6/install.md
  content/en/docs/v3.7/install.md
Labels: size/S, approved, needs-ok-to-test, lgtm

#1054 Addressing the different between content/en/docs/v3.6 and v3.7
  content/en/docs/v3.7/feature-gates/index.md
  content/en/docs/v3.7/quickstart.md
Labels: size/S, approved
