Repository etcd-io/website, pull requests merged in 2025-04, with the labels that each got.

#987 [v3.4] Update installation version to latest tag (v3.4.37)
  content/en/docs/v3.4/_index.md
Labels: size/XS, approved

#991 Mark the feature 'gRPC naming and discovery' as experimental
  content/en/docs/v3.5/dev-guide/grpc_naming.md
  content/en/docs/v3.6/dev-guide/grpc_naming.md
Labels: size/S, approved

#973 Add changes in `embed.EtcdServer` struct for feature gate.
  content/en/docs/v3.6/feature-gates/index.md
Labels: approved, size/M
