Repository etcd-io/website, pull requests merged in 2025-06, with the labels that each got.

#1011 Disable markdownlint MD052 rule
  .markdownlint-cli2.yaml
Labels: size/XS, approved, do-not-merge/hold

#1007 Fix incorrect description of InitialCorruptCheck and TxnModeWriteWithSharedBuffer features
  content/en/docs/v3.6/feature-gates/index.md
Labels: size/XS, approved, ok-to-test

#1026 Disable exclude_search in _index.md (3.6)
  content/en/docs/v3.6/_index.md
Labels: size/XS, approved, ok-to-test

#1022 Fix the issue of incorrect description of "operations." in the TxnModeWriteWithSharedBuffer function
  content/en/docs/v3.6/feature-gates/index.md
Labels: size/XS, approved, ok-to-test

#1027 Add etcd-workbench link to tools
  content/en/docs/v3.2/integrations.md
  content/en/docs/v3.3/integrations.md
  content/en/docs/v3.4/integrations.md
  content/en/docs/v3.5/integrations.md
  content/en/docs/v3.6/integrations.md
Labels: approved, size/L, ok-to-test

#1025 Revise website tutorial how-to-transactional-write
  content/en/docs/v3.5/tutorials/how-to-transactional-write.md
  content/en/docs/v3.6/tutorials/how-to-transactional-write.md
Labels: approved, size/M, ok-to-test

#1034 Update next redirect to etcd 3.7 documentation
  layouts/index.redirects
Labels: size/XS, approved, lgtm
