Repository etcd-io/website, pull requests merged in 2025-01, with the labels that each got.

#937 Fix typo
  content/en/docs/v3.5/learning/persistent-storage-files.md
  content/en/docs/v3.6/learning/persistent-storage-files.md
Labels: size/XS, approved, ok-to-test

#938 Promote ivanvc to approver for etcd website
  OWNERS
Labels: area/community, size/XS, approved, lgtm

#943 fix leases broken link
  content/en/docs/v3.4/learning/api_guarantees.md
  content/en/docs/v3.5/learning/api_guarantees.md
  content/en/docs/v3.5/learning/why.md
  content/en/docs/v3.6/learning/api_guarantees.md
  content/en/docs/v3.6/learning/why.md
Labels: size/S, approved, ok-to-test

#946 Update npm dependencies
  package.json
Labels: size/XS, approved

#941 Add feature gates doc for etcd
  content/en/docs/v3.6/feature-gates/index.md
Labels: approved, size/M, ok-to-test

#947 Remove refs to `latest` container tags
  content/en/docs/v3.4/op-guide/container.md
  content/en/docs/v3.5/op-guide/container.md
  content/en/docs/v3.5/op-guide/kubernetes.md
  content/en/docs/v3.6/op-guide/container.md
  content/en/docs/v3.6/op-guide/kubernetes.md
Labels: approved, size/M, ok-to-test

#949 [v3.5] Update installation version to latest tag (v3.5.18)
  content/en/docs/v3.5/_index.md
Labels: size/XS, approved
