Repository etcd-io/website, pull requests merged in 2025-03, with the labels that each got.

#964 [v3.6] Updating api reference documentation
  content/en/docs/v3.6/dev-guide/api_concurrency_reference_v3.md
  content/en/docs/v3.6/dev-guide/api_reference_v3.md
Labels: approved, size/L, ok-to-test

#969 [v3.4] Update installation version to latest tag (v3.4.36)
  content/en/docs/v3.4/_index.md
Labels: size/XS, approved

#972 [v3.5] Update installation version to latest tag (v3.5.19)
  content/en/docs/v3.5/_index.md
Labels: size/XS, approved

#974 Add a blog post to summarize the issue in 3.5 to 3.6 upgrade
  content/en/blog/2025/upgrade_from_3.5_to_3.6_issue.md
Labels: approved, size/M

#976 [v3.5] Update installation version to latest tag (v3.5.21)
  content/en/docs/v3.5/_index.md
Labels: size/XS, approved
