Repository etcd-io/website, pull requests merged in 2025-05, with the labels that each got.

#967 Doc for upgrading to v3.6 from v3.5
  content/en/docs/v3.6/upgrades/upgrade_3_6.md
  content/en/docs/v3.6/upgrades/upgrading-etcd.md
Labels: approved, size/XL, lgtm, ok-to-test

#965 Add 3.6 downgrade instructions.
  content/en/docs/v3.6/downgrades/downgrade_3_6.md
  content/en/docs/v3.6/downgrades/downgrading-etcd.md
Labels: approved, size/L

#998 Add note about the requirement to upgrade to 3.5.20 first.
  content/en/docs/v3.6/upgrades/upgrade_3_6.md
Labels: size/XS, approved

#999 Add blog announcing-etcd-3.6.md
  content/en/blog/2025/announcing-etcd-3.6.md
  content/en/blog/2025/announcing-etcd-3.6/figure-1.png
  content/en/blog/2025/announcing-etcd-3.6/figure-2.png
  content/en/blog/2025/announcing-etcd-3.6/figure-3.png
  content/en/blog/2025/announcing-etcd-3.6/figure-4.png
  content/en/blog/2025/announcing-etcd-3.6/figure-5.png
Labels: approved, size/L, do-not-merge/hold

#979 Add section Embedding etcd in a Go Application
  content/en/docs/v3.5/dev-guide/golang_embed_pkg.md
  content/en/docs/v3.6/dev-guide/golang_embed_pkg.md
Labels: size/S, approved, ok-to-test

#1005 Update 3.6 release blog to clarify the extended support for v3.4
  content/en/blog/2025/announcing-etcd-3.6.md
Labels: size/XS, approved
